import numpy as np
#THIS CODE IS NOT OUR OWN BUT GENERATED BY CHAT GPT
# Step 1: Read the calculated lengths (f) from the file
f_values = []
with open("calculated_lengths.txt", "r") as file:
    for line in file:
        if "Calculated lengths (f):" in line:
            f_values = list(map(float, line.strip().split(":")[1].split()))

# Step 2: Compute the mean (mu)
mu = np.mean(f_values)

# Step 3: Compute the variance (sigma^2) using the formula
N = len(f_values)
variance = sum((f_i - mu) ** 2 for f_i in f_values) / (N - 1)

# Output the variance
print(f"Variance (σ²): {np.sqrt(variance)}")
print(mu)